name: "Bug Report"
description: "Report a bug or unexpected behavior in the project."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide a clear and concise description of the bug you encountered.

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the Bug"
      description: "What happened? Include any error messages or unexpected behavior."
      placeholder: "When I try to..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "I expected it to..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide step-by-step instructions to reproduce the bug."
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or Logs"
      description: "If applicable, add screenshots or logs to help explain the issue."
      placeholder: "Drag and drop images or paste logs here."
    validations:
      required: false

  - type: input
    id: system-info
    attributes:
      label: "System Information"
      description: "Provide details about your environment (OS, Java version, Minecraft version, etc.)."
      placeholder: "Windows 10, Java 8, Forge 1.8.9"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Checklist"
      description: "Before submitting, please confirm the following:"
      options:
        - label: "I have checked for existing bug reports."
          required: true
        - label: "I have provided detailed information."
          required: true
        - label: "I have attached logs or screenshots if applicable."
          required: false
