name: "Feature Request"
description: "Suggest a new feature or improvement for the project."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please provide a detailed description of the feature you'd like to see implemented.

  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Describe the feature and how it would improve the project."
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Explain how this feature would be useful in practical scenarios."
      placeholder: "This would be helpful when..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered other solutions or workarounds?"
      placeholder: "An alternative solution could be..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How urgent is this feature?"
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Checklist"
      description: "Before submitting, please confirm the following:"
      options:
        - label: "I have checked for existing feature requests."
          required: true
        - label: "I have provided sufficient details."
          required: true
